#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.


LoadSettings:   ; initial read from settings.ini
    {
        IniRead, TibiaClient, settings.ini, settings, TibiaClient
        ; <Tab 1
        IniRead, LoginHotkey1Tibia10, settings.ini, settings, LoginHotkey1Tibia10
        IniRead, LoginHotkey1Tibia11, settings.ini, settings, LoginHotkey1Tibia11
        IniRead, LoginHotkey2Tibia10, settings.ini, settings, LoginHotkey2Tibia10
        IniRead, LoginHotkey2Tibia11, settings.ini, settings, LoginHotkey2Tibia11
        IniRead, AutoReconnectTibia10, settings.ini, settings, AutoReconnectTibia10
        IniRead, AutoReconnectTibia11, settings.ini, settings, AutoReconnectTibia11
        IniRead, AccountNameReconnectTibia10, settings.ini, settings, AccountNameReconnectTibia10
        IniRead, AccountNameReconnectTibia11, settings.ini, settings, AccountNameReconnectTibia11
        IniRead, PasswordReconnectTibia10, settings.ini, settings, PasswordReconnectTibia10
        IniRead, PasswordReconnectTibia11, settings.ini, settings, PasswordReconnectTibia11
        IniRead, AccountNameReconnect2Tibia10, settings.ini, settings, AccountNameReconnect2Tibia10
        IniRead, AccountNameReconnect2Tibia11, settings.ini, settings, AccountNameReconnect2Tibia11
        IniRead, PasswordReconnect2Tibia10, settings.ini, settings, PasswordReconnect2Tibia10
        IniRead, PasswordReconnect2Tibia11, settings.ini, settings, PasswordReconnect2Tibia11
        IniRead, TimesToPressDownTibia10, settings.ini, settings, TimesToPressDownTibia10
        IniRead, TimesToPressDownTibia11, settings.ini, settings, TimesToPressDownTibia11
        IniRead, TimesToPressDown2Tibia10, settings.ini, settings, TimesToPressDown2Tibia10
        IniRead, TimesToPressDown2Tibia11, settings.ini, settings, TimesToPressDown2Tibia11
        IniRead, KeepTibia10ClientActive, settings.ini, settings, KeepTibia10ClientActive
        IniRead, KeepTibia11ClientActive, settings.ini, settings, KeepTibia11ClientActive
        IniRead, PressFXEveryXms1Tibia10, settings.ini, settings, PressFXEveryXms1Tibia10
        IniRead, PressFXEveryXms2Tibia10, settings.ini, settings, PressFXEveryXms2Tibia10
        IniRead, PressFXEveryXms3Tibia10, settings.ini, settings, PressFXEveryXms3Tibia10
        IniRead, PressFXEveryXms1DelayTibia10, settings.ini, settings, PressFXEveryXms1DelayTibia10
        IniRead, PressFXEveryXms2DelayTibia10, settings.ini, settings, PressFXEveryXms2DelayTibia10
        IniRead, PressFXEveryXms3DelayTibia10, settings.ini, settings, PressFXEveryXms3DelayTibia10
        IniRead, PressFXEveryXms1HotkeyTibia10, settings.ini, settings, PressFXEveryXms1HotkeyTibia10
        IniRead, PressFXEveryXms2HotkeyTibia10, settings.ini, settings, PressFXEveryXms2HotkeyTibia10
        IniRead, PressFXEveryXms3HotkeyTibia10, settings.ini, settings, PressFXEveryXms3HotkeyTibia10
        IniRead, PressFXEveryXms1Tibia11, settings.ini, settings, PressFXEveryXms1Tibia11
        IniRead, PressFXEveryXms2Tibia11, settings.ini, settings, PressFXEveryXms2Tibia11
        IniRead, PressFXEveryXms3Tibia11, settings.ini, settings, PressFXEveryXms3Tibia11
        IniRead, PressFXEveryXms1DelayTibia11, settings.ini, settings, PressFXEveryXms1DelayTibia11
        IniRead, PressFXEveryXms2DelayTibia11, settings.ini, settings, PressFXEveryXms2DelayTibia11
        IniRead, PressFXEveryXms3DelayTibia11, settings.ini, settings, PressFXEveryXms3DelayTibia11
        IniRead, PressFXEveryXms1HotkeyTibia11, settings.ini, settings, PressFXEveryXms1HotkeyTibia11
        IniRead, PressFXEveryXms2HotkeyTibia11, settings.ini, settings, PressFXEveryXms2HotkeyTibia11
        IniRead, PressFXEveryXms3HotkeyTibia11, settings.ini, settings, PressFXEveryXms3HotkeyTibia11
        IniRead, PressHotkeyWhenFullManaTibia10, settings.ini, settings, PressHotkeyWhenFullManaTibia10
        IniRead, ShiftFullManaTibia10, settings.ini, settings, ShiftFullManaTibia10
        IniRead, PressHotkeyWhenFullManaTibia11, settings.ini, settings, PressHotkeyWhenFullManaTibia11
        IniRead, ShiftFullManaTibia11, settings.ini, settings, ShiftFullManaTibia11
        IniRead, PressHotkeyWhenFullManaHotkeyTibia10, settings.ini, settings, PressHotkeyWhenFullManaHotkeyTibia10
        IniRead, PressHotkeyWhenFullManaHotkeyTibia11, settings.ini, settings, PressHotkeyWhenFullManaHotkeyTibia11
        IniRead, EatFoodTibia11, settings.ini, settings, EatFoodTibia11
        IniRead, EatFoodHotkeyTibia11, settings.ini, settings, EatFoodHotkeyTibia11
        IniRead, ShiftEatFoodTibia11, settings.ini, settings, ShiftEatFoodTibia11
        IniRead, RightClickHold, settings.ini, settings, RightClickHold
        IniRead, RightClickHoldDelay, settings.ini, settings, RightClickHoldDelay
        IniRead, AntiIdleTibia10, settings.ini, settings, AntiIdleTibia10
        IniRead, AntiIdleTibia11, settings.ini, settings, AntiIdleTibia11
        IniRead, AntiIdleDelayTibia10, settings.ini, settings, AntiIdleDelayTibia10
        IniRead, AntiIdleDelayTibia11, settings.ini, settings, AntiIdleDelayTibia11
        IniRead, AntiIdleBackgroundTibia10, settings.ini, settings, AntiIdleBackgroundTibia10
        IniRead, AntiIdleBackgroundTibia11, settings.ini, settings, AntiIdleBackgroundTibia11
        IniRead, LogoffIfBattleChangesTibia10, settings.ini, settings, LogoffIfBattleChangesTibia10
        IniRead, LogoffIfBattleChangesTibia11, settings.ini, settings, LogoffIfBattleChangesTibia11
        ; Tab 1/>
        ; <Tab 2
        IniRead, Tibia10Directory, settings.ini, settings, Tibia10Directory
        IniRead, Tibia11Directory, settings.ini, settings, Tibia11Directory
        IniRead, ReopenTibia10Client, settings.ini, settings, ReopenTibia10Client
        IniRead, ReopenTibia11Client, settings.ini, settings, ReopenTibia11Client
        IniRead, MoveItemToGroundTibia10, settings.ini, settings, MoveItemToGroundTibia10
        IniRead, MoveItemToGroundTibia11, settings.ini, settings, MoveItemToGroundTibia11
        IniRead, MoveItemToBackpackTibia10, settings.ini, settings, MoveItemToBackpackTibia10
        IniRead, MoveItemToBackpackTibia11, settings.ini, settings, MoveItemToBackpackTibia11
        IniRead, MoveItemToBackpackHotkeyTibia10, settings.ini, settings, MoveItemToBackpackHotkeyTibia10
        IniRead, MoveItemToBackpackHotkeyTibia11, settings.ini, settings, MoveItemToBackpackHotkeyTibia11
        IniRead, MoveItemToGroundHotkeyTibia10, settings.ini, settings, MoveItemToGroundHotkeyTibia10
        IniRead, MoveItemToGroundHotkeyTibia11, settings.ini, settings, MoveItemToGroundHotkeyTibia11
        IniRead, BPPosXTibia10, settings.ini, settings, BPPosXTibia10
        IniRead, BPPosXTibia11, settings.ini, settings, BPPosXTibia11
        IniRead, BPPosYTibia10, settings.ini, settings, BPPosYTibia10
        IniRead, BPPosYTibia11, settings.ini, settings, BPPosYTibia11
        IniRead, CharPosXTibia10, settings.ini, settings, CharPosXTibia10
        IniRead, CharPosYTibia10, settings.ini, settings, CharPosYTibia10
        IniRead, CharPosXTibia11, settings.ini, settings, CharPosXTibia11
        IniRead, CharPosYTibia11, settings.ini, settings, CharPosYTibia11
        IniRead, GamingMode, settings.ini, settings, GamingMode
        IniRead, RemapKey1Tibia10, settings.ini, settings, RemapKey1Tibia10
        IniRead, RemapKey2Tibia10, settings.ini, settings, RemapKey2Tibia10
        IniRead, RemapKey3Tibia10, settings.ini, settings, RemapKey3Tibia10
        IniRead, RemapKey4Tibia10, settings.ini, settings, RemapKey4Tibia10
        IniRead, RemapKey5Tibia10, settings.ini, settings, RemapKey5Tibia10
        IniRead, RemapKey6Tibia10, settings.ini, settings, RemapKey6Tibia10
        IniRead, RemapKey7Tibia10, settings.ini, settings, RemapKey7Tibia10
        IniRead, RemapKey8Tibia10, settings.ini, settings, RemapKey8Tibia10
        IniRead, RemapKey9Tibia10, settings.ini, settings, RemapKey9Tibia10
        IniRead, RemapKey10Tibia10, settings.ini, settings, RemapKey10Tibia10
        IniRead, RemapKey1RemapTibia10, settings.ini, settings, RemapKey1RemapTibia10
        IniRead, RemapKey2RemapTibia10, settings.ini, settings, RemapKey2RemapTibia10
        IniRead, RemapKey3RemapTibia10, settings.ini, settings, RemapKey3RemapTibia10
        IniRead, RemapKey4RemapTibia10, settings.ini, settings, RemapKey4RemapTibia10
        IniRead, RemapKey5RemapTibia10, settings.ini, settings, RemapKey5RemapTibia10
        IniRead, RemapKey64RemapTibia10, settings.ini, settings, RemapKey6RemapTibia10
        IniRead, RemapKey7RemapTibia10, settings.ini, settings, RemapKey7RemapTibia10
        IniRead, RemapKey8RemapTibia10, settings.ini, settings, RemapKey8RemapTibia10
        IniRead, RemapKey9RemapTibia10, settings.ini, settings, RemapKey9RemapTibia10
        IniRead, RemapKey10RemapTibia10, settings.ini, settings, RemapKey10RemapTibia10
        ; Tab 2/>
        ; <Tab 3
        IniRead, EquipRoHTibia10, settings.ini, settings, EquipRoHTibia10
        IniRead, EquipRoHTibia11, settings.ini, settings, EquipRoHTibia11
        IniRead, EquipLifeRingTibia10, settings.ini, settings, EquipLifeRingTibia10
        IniRead, EquipLifeRingTibia11, settings.ini, settings, EquipLifeRingTibia11
        IniRead, EquipTimeRingTibia10, settings.ini, settings, EquipTimeRingTibia10
        IniRead, EquipTimeRingTibia11, settings.ini, settings, EquipTimeRingTibia11
        IniRead, EquipDwarvenRingTibia10, settings.ini, settings, EquipDwarvenRingTibia10
        IniRead, EquipDwarvenRingTibia11, settings.ini, settings, EquipDwarvenRingTibia11
        IniRead, EquipSSATibia10, settings.ini, settings, EquipSSATibia10
        IniRead, EquipSSATibia11, settings.ini, settings, EquipSSATibia11
        IniRead, DefaultAmuletTibia10, settings.ini, settings, DefaultAmuletTibia10
        IniRead, DefaultAmuletTibia11, settings.ini, settings, DefaultAmuletTibia11
        IniRead, DefaultRingTibia10, settings.ini, settings, DefaultRingTibia10
        IniRead, DefaultRingTibia11, settings.ini, settings, DefaultRingTibia11
        IniRead, DefaultSupportSpellTibia10, settings.ini, settings, DefaultSupportSpellTibia10
        IniRead, DefaultSupportSpellTibia11, settings.ini, settings, DefaultSupportSpellTibia11
        IniRead, DefaultHasteSpellTibia10, settings.ini, settings, DefaultHasteSpellTibia10
        IniRead, DefaultHasteSpellTibia11, settings.ini, settings, DefaultHasteSpellTibia11
        IniRead, EquipLifeRingHotkeyTibia10, settings.ini, settings, EquipLifeRingHotkeyTibia10
        IniRead, EquipLifeRingHotkeyTibia11, settings.ini, settings, EquipLifeRingHotkeyTibia11
        IniRead, EquipRoHHotkeyTibia10, settings.ini, settings, EquipRoHHotkeyTibia10
        IniRead, EquipRoHHotkeyTibia11, settings.ini, settings, EquipRoHHotkeyTibia11
        IniRead, EquipTimeRingHotkeyTibia10, settings.ini, settings, EquipTimeRingHotkeyTibia10
        IniRead, EquipTimeRingHotkeyTibia11, settings.ini, settings, EquipTimeRingHotkeyTibia11
        IniRead, EquipDwarvenRingHotkeyTibia10, settings.ini, settings, EquipDwarvenRingHotkeyTibia10
        IniRead, EquipDwarvenRingHotkeyTibia11, settings.ini, settings, EquipDwarvenRingHotkeyTibia11
        IniRead, EquipSSAHotkeyTibia10, settings.ini, settings, EquipSSAHotkeyTibia10
        IniRead, EquipSSAHotkeyTibia11, settings.ini, settings, EquipSSAHotkeyTibia11
        IniRead, ShiftEquipLifeRingTibia10, settings.ini, settings, ShiftEquipLifeRingTibia10
        IniRead, ShiftEquipLifeRingTibia11, settings.ini, settings, ShiftEquipLifeRingTibia11
        IniRead, ShiftEquipRoHTibia10, settings.ini, settings, ShiftEquipRoHTibia10
        IniRead, ShiftEquipRoHTibia11, settings.ini, settings, ShiftEquipRoHTibia11
        IniRead, ShiftEquipTimeRingTibia10, settings.ini, settings, ShiftEquipTimeRingTibia10
        IniRead, ShiftEquipTimeRingTibia11, settings.ini, settings, ShiftEquipTimeRingTibia11
        IniRead, ShiftEquipDwarvenRingTibia10, settings.ini, settings, ShiftEquipDwarvenRingTibia10
        IniRead, ShiftEquipDwarvenRingTibia11, settings.ini, settings, ShiftEquipDwarvenRingTibia11
        IniRead, ShiftEquipSSATibia10, settings.ini, settings, ShiftEquipSSATibia10
        IniRead, ShiftEquipSSATibia11, settings.ini, settings, ShiftEquipSSATibia11
        IniRead, ShiftUtamoVitaTibia10, settings.ini, settings, ShiftUtamoVitaTibia10
        IniRead, ShiftUtamoVitaTibia11, settings.ini, settings, ShiftUtamoVitaTibia11
        IniRead, RenewUtamoVitaTibia10, settings.ini, settings, RenewUtamoVitaTibia10
        IniRead, RenewUtamoVitaTibia11, settings.ini, settings, RenewUtamoVitaTibia11
        IniRead, RenewUtaniHurTibia10, settings.ini, settings, RenewUtaniHurTibia10
        IniRead, RenewUtaniHurTibia11, settings.ini, settings, RenewUtaniHurTibia11
        IniRead, RenewUtaniGranHurTibia10, settings.ini, settings, RenewUtaniGranHurTibia10
        IniRead, RenewUtaniGranHurTibia11, settings.ini, settings, RenewUtaniGranHurTibia11
        IniRead, RenewUtaniTempoHurTibia10, settings.ini, settings, RenewUtaniTempoHurTibia10
        IniRead, RenewUtaniTempoHurTibia11, settings.ini, settings, RenewUtaniTempoHurTibia11
        IniRead, RenewUtamoTempoSanTibia10, settings.ini, settings, RenewUtamoTempoSanTibia10
        IniRead, RenewUtamoTempoSanTibia11, settings.ini, settings, RenewUtamoTempoSanTibia11
        IniRead, UtamoVitaHotkeyTibia10, settings.ini, settings, UtamoVitaHotkeyTibia10
        IniRead, UtamoVitaHotkeyTibia11, settings.ini, settings, UtamoVitaHotkeyTibia11
        IniRead, UtaniHurHotkeyTibia10, settings.ini, settings, UtaniHurHotkeyTibia10
        IniRead, UtaniHurHotkeyTibia11, settings.ini, settings, UtaniHurHotkeyTibia11
        IniRead, UtaniGranHurHotkeyTibia10, settings.ini, settings, UtaniGranHurHotkeyTibia10
        IniRead, UtaniGranHurHotkeyTibia11, settings.ini, settings, UtaniGranHurHotkeyTibia11
        IniRead, UtaniTempoHurHotkeyTibia10, settings.ini, settings, UtaniTempoHurHotkeyTibia10
        IniRead, UtaniTempoHurHotkeyTibia11, settings.ini, settings, UtaniTempoHurHotkeyTibia11
        IniRead, UtamoTempoSanHotkeyTibia10, settings.ini, settings, UtamoTempoSanHotkeyTibia10
        IniRead, UtamoTempoSanHotkeyTibia11, settings.ini, settings, UtamoTempoSanHotkeyTibia11
        IniRead, ShiftUtaniHurTibia10, settings.ini, settings, ShiftUtaniHurTibia10
        IniRead, ShiftUtaniHurTibia11, settings.ini, settings, ShiftUtaniHurTibia11
        IniRead, ShiftUtaniGranHurTibia10, settings.ini, settings, ShiftUtaniGranHurTibia10
        IniRead, ShiftUtaniGranHurTibia11, settings.ini, settings, ShiftUtaniGranHurTibia11
        IniRead, ShiftUtaniTempoHurTibia10, settings.ini, settings, ShiftUtaniTempoHurTibia10
        IniRead, ShiftUtaniTempoHurTibia11, settings.ini, settings, ShiftUtaniTempoHurTibia11
        IniRead, ShiftUtamoTempoSanTibia10, settings.ini, settings, ShiftUtamoTempoSanTibia10
        IniRead, ShiftUtamoTempoSanTibia11, settings.ini, settings, ShiftUtamoTempoSanTibia11
        ; Tab 3/>
        ; <Tab 4
        IniRead, AccountNameMC1, settings.ini, settings, AccountNameMC1
        IniRead, PasswordMC1, settings.ini, settings, PasswordMC1
        IniRead, TimesToPressDownMC1, settings.ini, settings, TimesToPressDownMC1
        IniRead, AccountNameMC2, settings.ini, settings, AccountNameMC2
        IniRead, PasswordMC2, settings.ini, settings, PasswordMC2
        IniRead, TimesToPressDownMC2, settings.ini, settings, TimesToPressDownMC2
        IniRead, AccountNameMC3, settings.ini, settings, AccountNameMC3
        IniRead, PasswordMC3, settings.ini, settings, PasswordMC3
        IniRead, TimesToPressDownMC3, settings.ini, settings, TimesToPressDownMC3
        IniRead, AccountNameMC4, settings.ini, settings, AccountNameMC4
        IniRead, PasswordMC4, settings.ini, settings, PasswordMC4
        IniRead, TimesToPressDownMC4, settings.ini, settings, TimesToPressDownMC4
        IniRead, AccountNameMC5, settings.ini, settings, AccountNameMC5
        IniRead, PasswordMC5, settings.ini, settings, PasswordMC5
        IniRead, TimesToPressDownMC5, settings.ini, settings, TimesToPressDownMC5
        ; Tab 4/>
        ; <Tab 5
        IniRead, TransparentOldBotTibia10, settings.ini, settings, TransparentOldBotTibia10
        IniRead, TransparentOldBotTibia11, settings.ini, settings, TransparentOldBotTibia11
        ; Tab 5/>
    }
